name: Build Master

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        java-version: [ '8' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1
      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
      - name: Build with gradle
        run: ./gradlew build --build-file build8.gradle.kts
      - uses: actions/upload-artifact@v1
        with:
          name: mobok8
          path: build/distributions/
