name: Build Master

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        java-version: [ '8', '11' ]
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Checkout Source Code
        uses: actions/checkout@v1
      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
      - name: Build >8 with gradle
        run: ./gradlew build
        if: matrix.java-version != '8'
      - name: Build 8 with gradle
        run: ./gradlew build --build-file build8.gradle.kts
        if: matrix.java-version == '8'
      - uses: actions/upload-artifact@v1
        with:
          name: mobok${{ matrix.java-version }}
          path: build/distributions/
      - name: Build base image
        run: echo VERSION
        if: "$VERSION" != ""
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}